//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyRh.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyRh.Exceptions.ResourceErrorMessage", typeof(ResourceErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cpf deve ser válido.
        /// </summary>
        public static string Invalid_Cpf_Format {
            get {
                return ResourceManager.GetString("Invalid_Cpf_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email deve ser válido.
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credênciais inválidas.
        /// </summary>
        public static string Invalid_Id {
            get {
                return ResourceManager.GetString("Invalid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da senha é inválido.
        /// </summary>
        public static string Invalid_Password_Format {
            get {
                return ResourceManager.GetString("Invalid_Password_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código postal deve ser válido.
        /// </summary>
        public static string Invalid_ZipCode {
            get {
                return ResourceManager.GetString("Invalid_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data de nascimento é obrigatório.
        /// </summary>
        public static string No_BirthDate {
            get {
                return ResourceManager.GetString("No_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo cidade é obrigatório.
        /// </summary>
        public static string No_City {
            get {
                return ResourceManager.GetString("No_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo país é obrigatório.
        /// </summary>
        public static string No_Country {
            get {
                return ResourceManager.GetString("No_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF é obrigatório.
        /// </summary>
        public static string No_Cpf {
            get {
                return ResourceManager.GetString("No_Cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email é obrigatório.
        /// </summary>
        public static string No_Email {
            get {
                return ResourceManager.GetString("No_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo d identificador da empresa é obrigatório.
        /// </summary>
        public static string No_Enterprise_Identifier {
            get {
                return ResourceManager.GetString("No_Enterprise_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome é obrigatório.
        /// </summary>
        public static string No_Name {
            get {
                return ResourceManager.GetString("No_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo senha é obrigatório.
        /// </summary>
        public static string No_Password {
            get {
                return ResourceManager.GetString("No_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de cargo é obrigatório.
        /// </summary>
        public static string No_Role {
            get {
                return ResourceManager.GetString("No_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo estado é obrigatório.
        /// </summary>
        public static string No_State {
            get {
                return ResourceManager.GetString("No_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo rua é obrigatório.
        /// </summary>
        public static string No_Street {
            get {
                return ResourceManager.GetString("No_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Código postal é obrigatório.
        /// </summary>
        public static string No_ZipCode {
            get {
                return ResourceManager.GetString("No ZipCode", resourceCulture);
            }
        }
    }
}
